### ISSUE TITLE
multi-doc yaml files show an error

### ISSUE THREAD

**Issue by yshavit** [vermut/intellij-ansible#10]
I've got this yaml file:

    one: two
    three: four
    ---
    five: six

The plugin reports an error at the first char of `---`:

> expected key-val pair or array item

This is a valid yaml file, since `---` separate yaml docs within a single stream, as illustrated in this yaml snippet:

    >>> import yaml
    >>> yaml_content = '''
    ... one: two
    ... three: four
    ... ---
    ... five: six
    ... '''
    >>> for yaml_doc in yaml.load_all(yaml_content):
    ...     print yaml_doc
    ...
    ...
    {'three': 'four', 'one': 'two'}
    {'five': 'six'}

**Comment by vermut** [comment]
Totally acknowledge this problem. I was too lazy to implement proper multi-doc parser. Care to take a look?

**Comment by yshavit** [comment]
Sure! I probably won't get to it soon (busy week), but I'll take a look when I can!

**Comment by vermut** [comment]
I made a different Yaml parser plugin. It does not include any Ansible functionality but parses YAML really good. Can you [try it](https://github.com/vermut/intellij-snakeyaml/raw/master/intellij-snakeyaml.zip) and see if it works better?

**Comment by yshavit** [comment]
Ah, that one works great! Thank you. :) I'll close this issue, feel free to reopen it if you like -- but for me the issue is resolved.
