### ISSUE TITLE
Ansible Schema validation: Incompatible types. Required: array. Actual: object

### ISSUE THREAD

**Issue by MacFlurry** [vermut/intellij-ansible#104]
Hello,

In a playbook,
the handlers section throws a warning:
[see screenshot](https://imgur.com/E2gUBvY)

what the plugin sees:
handlers: 
>array

name: 
>Schema validation: Incompatible types. Required: array. Actual: object. 

shell:
>Schema validation: Incompatible types. Required: array. Actual: object. 

etc.
yet in the tasks:
name is well recognized as string

I ran it through a **YAML validator** and there are **no errors**.
The playbook runs well.

Is it possible to fix this?

Best regards

**Comment by vermut** [comment]
It is very strange. I don't validate any schemas in this plugin. I think this is caused by something else. Maybe you have another plugin that does something with Yaml?

**Comment by MacFlurry** [comment]
Yeah, you’re right.
Another plugin did something.
I removed it.
thank you for taking on your time ! 👍🏽 

Best regards

**Comment by Pepan** [comment]
@vermut I have same problem - what plugin was the reason ?

**Comment by Pepan** [comment]
hmmm I just disabled all plugins, restarted IDE but problem is still here ...

**Comment by JSMichaud** [comment]
I just worked my way through this issue and figured out that the IDE was downloading "schemas" automatically and validating my YML files against them depending on what I had named my file.  This can be controlled/disabled under Languages & Frameworks -> Schemas and DTDs -> Remote JSON Schemas.
