### ISSUE TITLE
Unable to save changed colors & fonts

### ISSUE THREAD

**Issue by janreges** [vermut/intellij-ansible#11]
Hi vermut,

thank you for your plugin :)

Issue in *Editor -> Colors & Fonts -> YAML/Ansible*: when I uncheck "Use inherited attributes" and then I choose my favorite color for "Identifier" after click on "Apply", all my settings are reverted to defaults with checked "Use inherited attributes".

**Comment by vermut** [comment]
Works with me, IDEA Community, 0.7.3. Have you copied the read-only default schema? What versions of... everything are you using?

**Comment by vtsingaras** [comment]
I'm having the same issue.
