### ISSUE TITLE
Add support for Node tags.

### ISSUE THREAD

**Issue by peter-lawrey** [vermut/intellij-ansible#19]
This defines how types can be used in Yaml.

http://www.yaml.org/spec/1.2/spec.html#id2784064

e.g. 
```yaml
%TAG !e! tag:example.com,2000:app/
---
- !local foo
- !!str bar
- !e!tag%21 baz
```
However, the parser complains "unexpected token: BAD_CHARACTER"

**Comment by vermut** [comment]
I made a different Yaml parser plugin. It does not include any Ansible functionality but parses YAML really good. Can you [try it](https://github.com/vermut/intellij-snakeyaml/raw/master/intellij-snakeyaml.zip) and see if it works better?
