### ISSUE TITLE
Incorrect processing cases

### ISSUE THREAD

**Issue by timka-s** [vermut/intellij-ansible#20]
False Negative:

    my_root:
        ~my_key[some]: 123
        my_null_key:

False Positive:

    my_root:
    -   my_item
        my_key: my_value

**Comment by vermut** [comment]
And the expected result is..?

**Comment by timka-s** [comment]
Expected result for "false negative" is no error, because it's just 

    {
        "my_root": {
            "~my_key[some]": 123,
            "my_null_key": null
        }
    }

And for "false positive" expected behavior is error.

Example from python3:

    import yaml
    yaml.load('''
        my_root:
        -   my_item
            my_key: my_value
    ''')

Raises at line 3: "yaml.scanner.ScannerError: mapping values are not allowed here"

**Comment by vermut** [comment]
I made a different Yaml parser plugin. It does not include any Ansible functionality but parses YAML really good. Can you [try it](https://github.com/vermut/intellij-snakeyaml/raw/master/intellij-snakeyaml.zip) and see if it works better?
