### ISSUE TITLE
Collapsing works badly

### ISSUE THREAD

**Issue by yfried-redhat** [vermut/intellij-ansible#21]
When using the collapsing option (`ctrl+shift+(+/-)`) only string values are collapsed instead of entire dicts.
This is problematic because the best feature of the built-in YAML plugin allows to collapse long files and review them comfortably by sections. Using this plugin replaces this feature with the above mentioned behavior, which doesn't offer much usage.

**Comment by yfried-redhat** [comment]
Hi,
Is this issue properly explained? If something is unclear, please let me know.
 I'd really like to start using this plugin, but I can't until the folding is fixed.

tnx
Yair

**Comment by vermut** [comment]
I don't have enough time to fix it. Right now I'm trying to hire someone to finish this work.

**Comment by yfried-redhat** [comment]
Thank you for the update. good luck.

**Comment by yfried-redhat** [comment]
Hi @vermut,
Do you have any updates about this issue?

**Comment by vermut** [comment]
The "yaml/ansible" plugin is faar from complete YAML implementation. Because of this collapsing cannot understand actual regions of nodes.

I started another project plugin "SnakeYAML". It has everything and it's YAML complete. But no Ansible support.

Eventually I hope to merge them together, but it will take months at current pace. Without help. Alone. In the dark. Cold. My God, My God, Why Have You Forsaken Me?

**Comment by yfried-redhat** [comment]
@vermut,
How is snake-yaml different from default YAML plugin in professional edition?

**Comment by vermut** [comment]
Well, let me answer with a pictures:

![bad token](https://cloud.githubusercontent.com/assets/779376/12814225/1b66a2ce-cb46-11e5-9764-6477eb2aa16c.png)
![multiline](https://cloud.githubusercontent.com/assets/779376/12814226/1b66d03c-cb46-11e5-9dd1-16e904b54aee.png)
![aliases](https://cloud.githubusercontent.com/assets/779376/12814224/1b66888e-cb46-11e5-9a6f-f9fd663ae6c8.png)

In other words - SnakeYAML parses and validates. IdeaYAML - highlights known structures (key: value, multi-line)

**Comment by yfried-redhat** [comment]
Does it fold yaml properly?

Regards
Yair

**Comment by vermut** [comment]
Sure it folds.

**Comment by yfried-redhat** [comment]
Hi,
For me it still collapses only the last string of each element.
Could you please help me find out why?

![screenshot from 2016-10-13 10-13-54](https://cloud.githubusercontent.com/assets/5310525/19339735/cda4ea7e-912d-11e6-8e68-7bc621dd92a1.png)

Details:
Fedora 24
PyCharm 2016.2.3
Build #PY-162.1967.10, built on September 7, 2016
JRE: 1.8.0_112-release-b343 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

SnakeYaml Version: 1.17.0
YAML/Ansible Version: 0.9.4

Regards
Yair

**Comment by vermut** [comment]
I think your files are associated with Ansible. You have to choose between Ansible support and correct YAML/folding.

**Comment by yfried-redhat** [comment]
I've tried using only snakeyaml and got the same result
