### ISSUE TITLE
Refactoring Ansible variables

### ISSUE THREAD

**Issue by geoand** [vermut/intellij-ansible#25]
I have been using this plugin and works great!

One thing however that does not work for me is the renaming of Ansible variables (via Shift+F6).
Although the dialog does up and I am able to select a new name, however the name I select never gets used.

Thanks,
George

**Comment by vermut** [comment]
I know. But I don't have time right now for this. Maybe someone else will take this...

**Comment by geoand** [comment]
Thanks for the update!
