### ISSUE TITLE
support for cloud-config YAML?

### ISSUE THREAD

**Issue by streamnsight** [vermut/intellij-ansible#29]
Hello,

Seems like the cloud-config YAML extends a bit on the format here, and I wish it was working better for those. 
Not sure how to write / update PyCharm plugins but I would with some guidance.

Cloud config files tend to include files that are labeled with a 
key: | <--- that's a vertical bar
<--- content here.... --->

example:
```
 - name: docker-tcp.socket
      command: start
      enable: true
      content: |
        [Unit]
        Description=Docker Socket for the API
        [Socket]
        ListenStream=2375
        Service=docker.service
        BindIPv6Only=both
        [Install]
        WantedBy=sockets.target
```
and this plugin doesn't like this.

How can it be enhanced to support this markup?

Thanks

**Comment by vermut** [comment]
I made a different Yaml parser plugin. It does not include any Ansible functionality but parses YAML really good. Can you [try it](https://github.com/vermut/intellij-snakeyaml/raw/master/intellij-snakeyaml.zip) and see if it works better?
