### ISSUE TITLE
Does not work when Python plugin is activated

### ISSUE THREAD

**Issue by seiti** [vermut/intellij-ansible#35]
Python plugin depends on `YAML` plugin, but  `YAML/Ansible` does not work if `YAML` plugin is activated.

**Comment by vermut** [comment]
Are we talking about IDEA CE? Or Ultimate?

**Comment by LuizGsa21** [comment]
I just installed this plugin and was having the same issue. I fixed it by going to `Preferences > Editor > File Types` and moved `YAML` registered patterns to `YAML/Ansible`.

I'm using ultimate edition.
