### ISSUE TITLE
Class tags aren't recognized

### ISSUE THREAD

**Issue by cowboygneox** [vermut/intellij-ansible#38]
YAML recognizes using a class tags. In my case, I want to use `!class` at the top of the file to make it easy for SnakeYAML to parse. Also, I use `!!binary` in another place, and the plugin isn't happy with that either.

It would be nice to fix this.

**Comment by vermut** [comment]
Maybe you want to use SnakeYAML plugin instead?

**Comment by cowboygneox** [comment]
@vermut You're right; apparently I got confused as to who covers what.
