### ISSUE TITLE
intellij 16 compatibility ?

### ISSUE THREAD

**Issue by binarytemple** [vermut/intellij-ansible#44]
The plugin doesn't seem to be loading - i notice there is a built in yaml plugin. Could it be in conflict with intellij-ansible or is something else at play? I will try building from source but if in the meantime there is something you would like me to check please ping me via this issue.

**Comment by vermut** [comment]
Those editions already include basic YAML support. In case you want to enable this plugin, you'll need to reassign file type mappings:

Go to `Preferences > Editor > File Types` and move `YAML` registered patterns to `Ansible/YAML`.
