### ISSUE TITLE
Improperly color of curly brackets

### ISSUE THREAD

**Issue by swasher** [vermut/intellij-ansible#45]
I use a dark theme "Darkula" and this bug is very annoying. I think it becouse "double curly brackets" not match brackets pattern. When select "Sign: brace, comma, etc." it should be allocated by rectangle but it not.
![curly_brackets](https://cloud.githubusercontent.com/assets/1525918/14180030/05b7ff5e-f76a-11e5-807f-a3d96b32d715.png)

**Comment by vermut** [comment]
I thought is more a feature than a bug - ability to specify two different colours for simple brackets and Jinja inclusions.

Or you are saying that the **default** darcula colour for '{{' is bad?

**Comment by swasher** [comment]
Sorry, you are right - on default Darkula it's allright. My mistake. Please close.
