### ISSUE TITLE
memory limit issue

### ISSUE THREAD

**Issue by chechuironman** [vermut/intellij-ansible#46]
hey,

Since yesterday my PyCharm crashed for memory limit, I didint do any update that I know..I was working in a project I've been working in teh last 2 weeks, I use your plugin for ansible. I was copy/pasting and I got the memory crash that I enclose. I use mac. I can not open the project again cause I hit the memory limit, I even increased the limit but I still hitting it...any idea? 

PS: I use the community edition

<img width="1439" alt="screen shot 2016-04-08 at 11 34 10" src="https://cloud.githubusercontent.com/assets/356667/14380126/343153de-fd7e-11e5-9dbf-115ea36d3e25.png">

**Comment by vermut** [comment]
As a workaround - reassign *.yml to plaintext in File Types.

About a solution - can you share the project so I can recreate the problem?
