### ISSUE TITLE
Plugin is not working in project

### ISSUE THREAD

**Issue by dainiax** [vermut/intellij-ansible#52]
Hello,

I was using your plugin for some time and it is great.
But decided to reinstall the Intellij IDEA 2016 community edition from the start.

And for some reasons plugin does not work e.g. no autocomplete for role, etc.

Any suggestion how to investigate/fix the problem?
Is it important for plugin if I create a new project, import existing one or just open a folder structure in IntelliJ?

Thanks

**Comment by vermut** [comment]
Are .yaml associated with Ansible/YAML in File Types?

**Comment by dainiax** [comment]
![ansible_yaml](https://cloud.githubusercontent.com/assets/1052841/17047353/01fd5bf2-4fd5-11e6-95ab-6406090e6b60.PNG)

@vermut Plugin was missing these extensions, added them, restarted the editor and still the same issue.
Any more thoughts?
Thanks

**Comment by dainiax** [comment]
![yaml_ansible_activated](https://cloud.githubusercontent.com/assets/1052841/17061666/53e85832-5038-11e6-9122-b625daa737e0.png)
@vermut Tried to install on three different laptops and even on PyCharm CE and file type added as '*.yml' Everywhere the same as in the attached screen and none of functionality is working.

**Comment by vermut** [comment]
Yeah. Trouble indeed. I see the same now in my IDEA CE 2016.2. Probably they changed something.

Can you test it on 2016.1 to see help me locate the problem?

**Comment by dainiax** [comment]
Looks like IDEA CE 2016.1.3 is working. Did not have full Ansible project to test, but basic autocomplete was working.

**Comment by dainiax** [comment]
Is it also working on PyCharm CE 2016.1.4
Will be using this version while you will find how to fix the issue,
Thanks!

**Comment by zelig81** [comment]
On 2016.1.4 it worked (before 2016.2 i had had that version) 
Ilya

**Comment by kyeha** [comment]
Same issue looks to be fixed https://github.com/juzna/intellij-neon/issues/40

**Comment by Koc** [comment]
@vermut hope this fix will be released soon in plugins marketplace.

**Comment by fxvende** [comment]
@vermut do you plan to build a new release until the end of this year, please ?

**Comment by vermut** [comment]
Any release? Because that issue was fixed and released long ago.
