### ISSUE TITLE
Wrong identifiers parsing

### ISSUE THREAD

**Issue by zelig81** [vermut/intellij-ansible#53]
Hi!
I found that after upgrade to PyCharm 2016.2 - identifiers in yaml started to be parsed wrongly. You get only first letter of the identifier:

![capture](https://cloud.githubusercontent.com/assets/2457469/17082698/0c0a111e-5190-11e6-9f43-ed37089b4207.PNG)

Please let me know if you need some further information

thank you,
Ilya

**Comment by dainiax** [comment]
Hi,

I think it is the same issue as https://github.com/vermut/intellij-ansible/issues/52
