### ISSUE TITLE
[Query] Use as a linter?

### ISSUE THREAD

**Issue by kwill** [vermut/intellij-ansible#57]
Is this tool intended to be usable as a linter (YAML validation and/or cleanup)?

**Comment by vermut** [comment]
No, don't think so. Better use it's sister project
vermut/intellij-snakeyaml, it's much closer to RFC

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by kwill** [comment]
Thanks!
