### ISSUE TITLE
Run configuration

### ISSUE THREAD

**Issue by rightaway** [vermut/intellij-ansible#59]
Under the 'Edit configurations' section it would be great if there were a way to add a run configuration for ansible. Right now I am using the Bash configuration, but the problem with that is that the output window has no colors so I can't tell at a glance what changed and what didn't. Or is there a way to get colors to appear in the console with a Bash configuration?

**Comment by vermut** [comment]
It's heavily dependent of platform and shell. 
Under windows I use this hack: https://github.com/vermut/intellij_cygwin/blob/master/terminal.xml#L3
