### ISSUE TITLE
Jinja2 Notation with Loops

### ISSUE THREAD

**Issue by nuarhu** [vermut/intellij-ansible#71]
Hi there,

this is a bit like #4 but it has been closed and the notation is using pipes so I'm creating a new issue for it. Rather then a fix I would be just fine to know if:

- the file extension should be *.j2 or *.y(a)ml
- which plugin should the file extension be assigned to (I have it assigned to YAML/Ansible but the other issue mentioned SnakeYAML, so I could it assign to that, as well - though the file contains Jinja2 notation)
- should I change something about the syntax to make it work better with the YAML/Ansible plugin? I would also be fine with that.

Current syntax which just makes everything after it go completely red and breaks all validation:

```
        url:
{% for host in groups['xxx'] %}
            - "http://{{ hostvars[host].do_private_ip_address }}:{{ port }}/"
{% endfor %}
```

Thanks for your work!

**Comment by vermut** [comment]
- Ansible/YAML has basic support for Jinja {{ vars }} and basic support for YAML (no fancy stuff).
- SnakeYAML has no Jinja and close-to-full support for YAML. 
- Before I die I might create YAML+Jinja2 version. But I'm still healthy and use workaround with YAML comments like that:

```
        url:
# This makes it YAML comment but Jinja still executed {% for host in groups['xxx'] %}
            - "http://{{ hostvars[host].do_private_ip_address }}:{{ port }}/"
# {% endfor %}
```
