### ISSUE TITLE
Go to declaration for import_tasks & include_tasks

### ISSUE THREAD

**Issue by szpak** [vermut/intellij-ansible#86]
Starting with Ansible [2.4](https://docs.ansible.com/ansible/2.4/import_tasks_module.html) `import_tasks` & `include_tasks` can be used to import/include tasks from a separate file in the same role. It would be great to be able to use "go to declaration" (CTRL-B, CTRL-left click) for them, the same like it is currently implemented for roles.

**Comment by vermut** [comment]
Yes, that looks doable.
