### ISSUE TITLE
Link to the Ansible documentation is outdated

### ISSUE THREAD

**Issue by hyrth** [vermut/intellij-ansible#89]
https://github.com/vermut/intellij-ansible/blob/67f815497b2d6d91a47e9970a6d7c9cd8795ba25/src/main/java/lv/kid/vermut/intellij/yaml/reference/AnsibleVariableValuesDocumentationProvider.java#L41

Hi,
the link to the Ansible Module documentation is outdated - it should be:
https://docs.ansible.com/ansible/latest/modules/{0}_module.html

**Comment by rfvermut** [comment]
fixed
