### ISSUE TITLE
Please put this plugin as " not maintained anymore"

### ISSUE THREAD

**Issue by cradules** [vermut/intellij-ansible#95]
This plugin is not working anymore on new releases as pycharm 2019.1.1. I have been trying to get it working, fallowing all the recommendation but when I looked over plugin code last commit is "Commits on May 31, 2017". If this is not maintained anymore, please let the ppl know about it.

Thank you!

**Comment by alitvak69** [comment]
There are no alternatives so far.  Pavel, can you at least ask someone to take over?  It is a good plugin.  I would take over if I knew Java enough.

**Comment by RobertKosten** [comment]
@rfvermut Can you please attach a LICENSE.md to the code? Then I will fork and try to fix the errors.

**Comment by rfvermut** [comment]
ok, I'll make it as free as possible. It's borrowed from neon plugin so I'll have to take their license. Anyway - feel free to join and participate, this is an opensource community project.

**Comment by rfvermut** [comment]
BTW, I made an update to 0.10.0, maybe it will fix those issues. Please report on that.

**Comment by alitvak69** [comment]
@rfvermut Github doesn't show your update to 0.10.0. It is still on 0.9.5.  I don't see any recent  commits other than a license file.

**Comment by rfvermut** [comment]
> @rfvermut Github doesn't show your update to 0.10.0. It is still on 0.9.5. I don't see any recent commits other than a license file.

Right... Pushed it.

**Comment by JHeinzde** [comment]
@rfvermut Are there any simple Issues that I could help with? I used this quite a bit and would be happy to improve this plugin.

**Comment by rfvermut** [comment]
@JHeinzde there are some issues which are hard to reproduce, like #100 #102 #101 
We can go an easy way and just add try/catch(ignore) around those blocks to minimize the noise. You can totally take them.
