### ISSUE TITLE
I can not found roles and Task PyCharm

### ISSUE THREAD

**Issue by estkae** [vermut/intellij-ansible#96]
<img width="457" alt="Bildschirmfoto 2019-04-25 um 13 19 38" src="https://user-images.githubusercontent.com/3465491/56792233-6e895880-6809-11e9-9cf7-db5d8b807dba.png">
i'm trying to work with the Ansible plugin YAML/Ansible support with Jinja2 tags. I don't think this works in PyCgarme. See example. I expect when I'm on a variable to find it in the corresponding file. But that's not possible. See appendix

**Comment by vermut** [comment]
Color scheme looks like stock Yaml plugin. Are you sure you have YAML files associates with YAML/Ansible?
