### ISSUE TITLE
Cannot navigate to roles/handlers

### ISSUE THREAD

**Issue by jnazander** [vermut/intellij-ansible#98]
Is this plugin supposed to allow ctrl+clicking on a role/handler to quickly go into that file? Because it doesn't work (Intellij IDEA 2018.2.2)

![image](https://user-images.githubusercontent.com/4726607/60870309-44a4d700-a239-11e9-809a-47f1c6e78f7f.png)

**Comment by rfvermut** [comment]
Please try version 0.10.0 and report if this works
